### ISSUE TITLE
Increase total supply of coins

### ISSUE THREAD

**Issue by arthur-1** [ombre-projects/ombre#10]
Increase the total supply of coins to ~1B. Assuming the coin is successful, this would make the value of each coin roughly equivalent to 1USD making it easier to use as a day-to-day currency.

There are also some psychological factors that indicate people would rather have many less valuable coins than few valuable coins (assuming the net value in both scenarios are the same).

**Comment by mrheinen** [comment]
Agreed. In this case we also need to increase the miner fee to keep the same emission rate.

**Comment by mrheinen** [comment]
(miner fee -> block reward)
