### ISSUE TITLE
Blockchain issues since new difficulty algorithm commit

### ISSUE THREAD

**Issue by penta1998** [ombre-projects/ombre#11]
The latest checkout seems to have issues with syncing the blockchain. Below is the output on a new ubuntu system, with the latest checkout.

SYNCHRONIZATION started
2018-Feb-17 17:41:08.584405 [P2P2][185.101.98.125:36436 INC]Sync data returned a new top block candidate: 3 -> 1838 [Your node is 1835 blocks (1 days) behind]
SYNCHRONIZATION started
2018-Feb-17 17:41:09.720657 [P2P6][185.101.98.125:19743 OUT]Sync data returned a new top block candidate: 3 -> 1838 [Your node is 1835 blocks (1 days) behind]
SYNCHRONIZATION started
2018-Feb-17 17:41:10.367036 [P2P7]ERROR /home/ombre/ombre/src/cryptonote_core/blockchain.cpp:3018 !!!!!!!!! difficulty overhead !!!!!!!!!
2018-Feb-17 17:41:11.265842 [P2P5]ERROR /home/ombre/ombre/src/cryptonote_core/blockchain.cpp:3018 !!!!!!!!! difficulty overhead !!!!!!!!!
2018-Feb-17 17:41:12.549619 [P2P2]ERROR /home/ombre/ombre/src/cryptonote_core/blockchain.cpp:3018 !!!!!!!!! difficulty overhead !!!!!!!!!

Doesn't seem to progress much after this.

**Comment by penta1998** [comment]
I assume that once the blockchain is reset, this should go away. But thought its better to report this anyway

**Comment by arthur-1** [comment]
Thanks for reporting that, I'll look into it.

**Comment by mrheinen** [comment]
This is solved: I reverted the change.  It's not a great idea to change the difficulty last minute. Instead if we want to change it we should do it in a hardfork.
