### ISSUE TITLE
Error message in cli daemon

### ISSUE THREAD

**Issue by Elektryon-Dev** [ombre-projects/ombre#23]
2018-Mar-08 09:24:08.858144 [P2P5]ERROR C:/msys64/home/niels/ombre-build/src/cryptonote_core/checkpoints.cpp:107 CHECKPOINT FAILED FOR HEIGHT 5000. EXPECTED HASH: <e838c077bc66356d9bb321d4eb60f0851ef766f0619ddc4c6568a0f149aacea0>, FETCHED HASH: <8ab89dd795c4bd6985902cb9caa6a4289eea9bb63b6463dd2a628a020285439b>
2018-Mar-08 09:24:08.859144 [P2P5]ERROR C:/msys64/home/niels/ombre-build/src/cryptonote_core/blockchain.cpp:3373 WARNING: local blockchain failed to pass a SumoPulse checkpoint, and you could be on a fork. You should either sync up from scratch, OR download a fresh blockchain bootstrap, OR enable checkpoint enforcing with the --enforce-dns-checkpointing command-line option
2018-Mar-08 10:25:20.867894 [P2P8]ERROR C:/msys64/home/niels/ombre-build/src/cryptonote_core/checkpoints.cpp:107 CHECKPOINT FAILED FOR HEIGHT 5000. EXPECTED HASH: <e838c077bc66356d9bb321d4eb60f0851ef766f0619ddc4c6568a0f149aacea0>, FETCHED HASH: <8ab89dd795c4bd6985902cb9caa6a4289eea9bb63b6463dd2a628a020285439b>
2018-Mar-08 10:25:20.868898 [P2P8]ERROR C:/msys64/home/niels/ombre-build/src/cryptonote_core/blockchain.cpp:3373 WARNING: local blockchain failed to pass a SumoPulse checkpoint, and you could be on a fork. You should either sync up from scratch, OR download a fresh blockchain bootstrap, OR enable checkpoint enforcing with the --enforce-dns-checkpointing command-line option

The daemon synced beyond this point, just wanted to point out the error.

**Comment by mrheinen** [comment]
Can you try again with the latest binaries ?

**Comment by mrheinen** [comment]
I found the problem:
https://github.com/ombre-projects/ombre/commit/0e50ecba56b289015333b3531d78fd3c65812a86
