### ISSUE TITLE
Need to setup at least 2 DNS nodes

### ISSUE THREAD

**Issue by Elektryon-Dev** [ombre-projects/ombre#24]
2018-Mar-08 22:54:35.683157 [P2P2]WARNING: no two valid OmbrePule DNS checkpoint records were received

**Comment by mrheinen** [comment]
Yeah this is weird - I've setup 2 DNS nodes actually but I think the responses are not what is expected.

**Comment by mrheinen** [comment]
Right this is because the two DNS servers aren't supporting DNSSEC.  I upgraded them but it takes some time for the DNSSEC to become active.
