### ISSUE TITLE
Remove "SumoPulse checkpoint" message, confusing new users

### ISSUE THREAD

**Issue by Bluecoreg** [ombre-projects/ombre#27]
The message: WARNING: local blockchain failed to pass a SumoPulse checkpoint, and you could be on a fork. You should either sync up from scratch, OR download a fresh blockchain bootstrap, OR enable checkpoint enforcing with the —enforce-dns-checkpointing command-line option

**Comment by mrheinen** [comment]
+1 I'm fixing this right now (making it work properly)
