### ISSUE TITLE
Payments above 1000 OMB fail

### ISSUE THREAD

**Issue by mrheinen** [ombre-projects/ombre#33]
Payments above 1000 OMB fail

[wallet/0 cashCdYTu]: transfer xxxxxx 1001
Wallet password: ********
** No mixin value specified, default mixin 10 will be used for this transaction.
No payment id is included with this transaction. Is this okay?  (Y/Yes/N/No): y
Error: unexpected error: ge_frombytes_vartime failed at 264
[wallet/0 cashCdYTu]:

**Comment by Elektryon-Dev** [comment]
It is not a definitive issue at 1000 OMB. I got it at 25,57,2k,3k it appears random.

**Comment by mrheinen** [comment]
The higher the funds transferred the more likely it fails. At 1000 I can send the funds with 1-3 tries.  Sending 5k is absolutely not working.

**Comment by mrheinen** [comment]
I tried making the payment with the GUI wallet and ombre-wallet-rpc gives an interesting error:

```
[20:31:22] [ERROR] [ombre-wallet-rpc]>>> 2018-Mar-23 20:31:22.267996 [RPC0]ERROR /home/xxxx/Coding/ombre-build/src/wallet/wallet_rpc_server.cpp:594 constructed tx too big: tx size = 342235 bytes, limit = 269736 bytes; retrying with smaller tx_size_target_factor = 0...
```

The limit comes from:

```
#define TRANSACTION_SIZE_LIMIT                          ((uint64_t) ((CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE * 110 / 100) - CRYPTONOTE_COINBASE_BLOB_RESERVED_SIZE))
```

The calculation is:

```
(((240 * 1024) * 110) / 100) - 600
269736
```

The relation to the amount of OMB being sent is the following: The more we try to send (from the dev wallet in this case) the more inputs are needed for the transaction. This is a problem especially with the dev wallet because all inputs are only 5.8 OMB (or so) which means you need a lot of them to transfer > 1000 OMB.

We need to increase this limit.

**Comment by mrheinen** [comment]
I'm testing the pull request in testnet right now
https://github.com/ombre-projects/ombre/pull/34

**Comment by mrheinen** [comment]
Ok tested the change and it works as expected. After the hardfork I can make the transaction that normally would get the ge_frombytes_vartime error.
