### ISSUE TITLE
Last block syncing occasionally hangs

### ISSUE THREAD

**Issue by mrheinen** [ombre-projects/ombre#41]
![photo5372829879583746329](https://user-images.githubusercontent.com/12248144/38767940-9ee70186-3feb-11e8-82f9-dbd044581041.jpg)

I remember this also happening occasionally with sumokoin. Ideally we get more insight in this problem by restarting the daemon with --log-level 4.

**Comment by mrheinen** [comment]
Here is another example:

seems stuck refreshing the last 3 blocks
Height 59065 / 59068
and it changes when a new block adds
Height 59066 / 59069

**Comment by exceler55** [comment]
me too
