### ISSUE TITLE
Wallet starts uncommanded refresh

### ISSUE THREAD

**Issue by Bathmat** [ombre-projects/ombre#44]
Both the wallet-cli and wallet-rpc start an uncommanded refresh about every minute from block 4000. Additionally, when opening a wallet that was previously closed and saved, the wallet starts refresh from block 4000.

I'm using the latest source code. Built from source today Apr. 14 on Ubuntu 16.04 server.

Edit: It appears to rescan/refresh from Block 0 without a command. Just looked like 4000, cause that's where my first tx was.

**Comment by Bathmat** [comment]
The wallet-cli also shows `unlocked balance: 0.000000000` after restoring from mnemonic and looking like it completed a refresh. However `status` shows: `Refreshed 1289/58830, syncing, daemon RPC v1.0` and is proceeding very slowly.

**Comment by mrheinen** [comment]
If you use the wallet from the previous release - do you still have this issue?

**Comment by Bathmat** [comment]
@SadBatman no issue with the previous version (which is what I switched back to). It appears to send txs successfully with the latest daemon without issues too.

I am still "syncing" the new wallet to see if these issues disappear, but it's been 3 hours and have only gotten to: `Refreshed 10788/59005, syncing, daemon RPC v1.0`

**Comment by mrheinen** [comment]
Good feedback. I'll review the code differences.

**Comment by Bathmat** [comment]
New issue with wallet-rpc:

```
2018-Apr-15 19:56:56.898671 [RPC0]ERROR /usr/local/src/ombre6/src/cryptonote_core/cryptonote_format_utils.cpp:607 Destinations have to have exactly one output to support encrypted payment ids
2018-Apr-15 19:56:56.898719 [RPC0]ERROR /usr/local/src/ombre6/src/wallet/wallet2.cpp:4206 !r. THROW EXCEPTION: error::tx_not_constructed
```
Not sure if this is just an issue with my pool's software or if it's the wallet-rpc issue.
