### ISSUE TITLE
Core Dumped Error

### ISSUE THREAD

**Issue by CoFix** [ombre-projects/ombre#51]
Hello Staff,

I am getting this error on install. How can i fix it?

2018-Apr-29 11:00:19.688680 Initializing cryptonote protocol...
2018-Apr-29 11:00:19.688950 Cryptonote protocol initialized OK
2018-Apr-29 11:00:19.689397 Initializing p2p server...
2018-Apr-29 11:00:19.994006 Set limit-up to 2048 kB/s
2018-Apr-29 11:00:19.994482 Set limit-down to 8192 kB/s
2018-Apr-29 11:00:19.994785 Set limit-up to 2048 kB/s
2018-Apr-29 11:00:19.995086 Set limit-down to 8192 kB/s
2018-Apr-29 11:00:19.995467 Binding on 0.0.0.0:19743
2018-Apr-29 11:00:19.995834 Net service bound to 0.0.0.0:19743
2018-Apr-29 11:00:19.996118 Attempting to add IGD port mapping.
2018-Apr-29 11:00:24.000925 No IGD was found.
2018-Apr-29 11:00:24.001013 P2p server initialized OK
2018-Apr-29 11:00:24.001122 Initializing core rpc server...
2018-Apr-29 11:00:24.001175 Binding on 127.0.0.1:19744
2018-Apr-29 11:00:24.001254 Core rpc server initialized OK on port: 19744
2018-Apr-29 11:00:24.001281 Initializing core...
2018-Apr-29 11:00:24.001465 Loading blockchain from folder /home/ombre/.ombre/lmdb ...
2018-Apr-29 11:00:24.001513 option: fast
2018-Apr-29 11:00:24.001528 option: async
2018-Apr-29 11:00:24.001540 option: 1000
2018-Apr-29 11:00:24.001831 Error attempting to retrieve a hard fork version at height 0 from the db: MDB_NOTFOUND: No matching key/data pair found
Aborted (core dumped)

**Comment by mrheinen** [comment]
Can you try and build with "make release-static" ?
