### ISSUE TITLE
Daemon Error

### ISSUE THREAD

**Issue by swanseahost** [ombre-projects/ombre#53]
Hi there, 

I am getting this error when trying to run the daemon

~/ombre/build/release/bin$ ./ombred
Creating the logger system
2018-May-23 23:50:17.517623 Initializing cryptonote protocol...
2018-May-23 23:50:17.517649 Cryptonote protocol initialized OK
2018-May-23 23:50:17.517885 Initializing p2p server...
2018-May-23 23:50:17.621092 Set limit-up to 2048 kB/s
2018-May-23 23:50:17.621233 Set limit-down to 8192 kB/s
2018-May-23 23:50:17.621292 Set limit-up to 2048 kB/s
2018-May-23 23:50:17.621358 Set limit-down to 8192 kB/s
2018-May-23 23:50:17.621464 Binding on 0.0.0.0:19743
2018-May-23 23:50:17.621563 Net service bound to 0.0.0.0:19743
2018-May-23 23:50:17.621578 Attempting to add IGD port mapping.
2018-May-23 23:50:21.626312 No IGD was found.
2018-May-23 23:50:21.626414 P2p server initialized OK
2018-May-23 23:50:21.626504 Initializing core rpc server...
2018-May-23 23:50:21.626546 Binding on 127.0.0.1:19744
2018-May-23 23:50:21.626721 Core rpc server initialized OK on port: 19744
2018-May-23 23:50:21.626774 Initializing core...
2018-May-23 23:50:21.626938 Loading blockchain from folder /home/miner/.ombre/lmdb ...
2018-May-23 23:50:21.627010 option: fast
2018-May-23 23:50:21.627025 option: async
2018-May-23 23:50:21.627144 option: 1000
2018-May-23 23:50:21.627463 Error attempting to retrieve a hard fork version at height 0 from the db: MDB_NOTFOUND: No matching key/data pair found
Aborted (core dumped)

Please can you help ?

Thanks

**Comment by mrheinen** [comment]
Build with:

make release-static

And you won't have this error.  You might need to do a new git pull for this.
