### ISSUE TITLE
persistent MDB hard for error

### ISSUE THREAD

**Issue by madouz** [ombre-projects/ombre#92]
I have compiled latest release and previous one with both giving an "Error attempting to retreive a hard fork version at height 0 from the db". I also read previous posts with no success. I'm on ubuntu 16.04 64 bit. Any fix available for this yet? Is it a DB error or connection to seeds?
![Ombred Screenshot](https://user-images.githubusercontent.com/24627386/56866391-d93cbe80-69d8-11e9-97a0-223aa448be17.png)

**Comment by yoosofan** [comment]
Your compilation may went wrong. You can use binary.
Remove .ombre/ and download the [pre-release](https://github.com/ombre-projects/ombre/archive/1.4.2.2.tar.gz)
If you want to compile pre-release, use latest commit.
Remember that the coin website is [ombre.ir](http://ombre.ir) , and I may change the repository place in future too.

**Comment by madouz** [comment]
I did compile it successfully with same error also with downloaded binary from github. Problem may be with code or network seed connections perhaps. I also noticed tradeogre wallets in maintenance. Can you provide list of seed nodes i can try it manually in terminal?

**Comment by yoosofan** [comment]
The latest commit of repo does not have any compile error if you use static release.
I compiled it on ubuntu 18 several times. Seed nodes are hard coded on the source code, no need to have them specifically, even you can find the exact commit which I changed them.
